name: Deploy to EC2
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout
      - name: Deplpoy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
            cd /project/nextjs-film
            git pull origin main
            npm install
            npm run build
            pm2 restart nextjs-film
          EOF
