name: Deploy to EC2
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deplpoy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.EC2_IP}}
          USER_NAME: ${{secrets.EC2_USER}}
        run: |

          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
            cd project/nextjs-film
            git pull origin main
            npm install
            npm run build
            pm2 restart nextjs-app
          EOF
